### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by maariaw** [tspaanan/resgshowroom#1]
Sovelluksen toiminnallisuus on jo hyvässä vaiheessa!

Olet eritellyt rakennetta jo sql-kyselyjen ja oikeuksien tarkistuksen osalta. Joitakin asioita saa toteutettua siistimmin, jos sovellusta refaktoroi vielä enemmän. Jos esimerkiksi mallisovelluksen tapaan erottelee tietokannan määrittelyn omaan db-moduuliinsa, sen voi tuoda importtina muihin moduuleihin, eikä sitä tarvitse laittaa argumenttina jokaiseen funktion kutsuun.

Olet pitkällä myös syötteiden validoinnissa. Huomasin, että vielä voi kuitenkin antaa tyhjän palautteen. Lisäksi voisi aina vaatia käyttäjiltä rekisteröinnissä parempia salasanoja.

Ehdottaisin myös käyttäjäroolin tallentamista sessioon. Tarvitsee ehkä vähemmän säätöä oikeuksien tarkistamisessa. Jos haluaa vielä enemmän panostaa tietoturvaan, voit katsoa matskuista ohjeet csrf-tokenin käyttöön.

Tietokantojen rakennetta voisi vielä parantaa lisäämällä “visible” kentän joihinkin tauluihin siltä varalta, että käyttäjä haluaisi poistaa sisältöä. Esimerkiksi kun toteutat avainsanojen lisäämisen, olisi mukava olla mahdollisuus myös niiden poistamiseen, vahinkojen varalta jos ei muuten.

Projekti vaikuttaa fiksulta ja käyttö on yksinkertaista. Käyttäjäystävällisyys tietysti paranee vielä kun ulkoasua ehtii vähän selkiyttää. Kiva että olet kommentoinut koodia, oli helppo seurata mitä tapahtuu.

**Comment by tspaanan** [comment]
Kiitos tästä palautteesta, koodasin tänään kaikki ehdotuksesi mukaan. Erityisesti tuo moduuleihin jako oli jäänyt itseäni askarruttamaan, mutta nyt ymmärrän tarkemmin miten Pythonin from <module> import <something> toimii, ja miten helposti se tarjoaa pääsyn moduulissa asetettuihin muuttujiin: koodin rakenne selkiytyi entisestään.
