### ISSUE TITLE
Vertaisarviointi / välipalautus 3

### ISSUE THREAD

**Issue by sonjamadetoja** [tspaanan/resgshowroom#2]
Hieno ja monimutkainen sovellus, joka vaikuttaa olevan melkein valmis. Pääosin mukava käyttää.

Vierailijana:
- Vaikuttaa hyvältä. Kun lähettää viestin, ei tule mitään varmistusta, menikö se perille.

Opiskelijana:
- Salasanavaatimukset voisi kertoa jo rekisteröitymissivulla, ettei tarvitse montaa kertaa yrittää.
- Reserve this topic -painike johtaa Internal Server Error -virheilmoitukseen. (osoite: https://resgshowroom.herokuapp.com/reserve_topic)
- Muuten toimii hyvin, rekisteröityminen, sisäänkirjautuminen ja uloskirjautuminen toimivat, tutkimusaiheet helppo löytää.

Tutkijana:
- Kirjoitusvirhe käyttäjätunnuksessa aiheutta Internal Server Error -virheilmoituksen.
- Kirjautuminen, sivun luominen ja sen toiminnot vaikuttavat toimivan hyvin.
- Kun haluaa muuttaa kuvaustekstiä, niin uusi teksti tulee vanhan päälle kirjoittaessa, eikä vanhaa voi jatkaa vaan se häviää.
- Uutta julkaisua lisättäessä virheellinen syöte (numerokentissä kirjaimia) aiheuttaa Internal Server Error virheilmoituksen. Syötteitä voisi tarkistaa, esimerkiksi että vuosi on oikeasti vuosiluku.
- Uuden tutkimusaiheen lisääminen toimii, mutta paikka ei ole intuitiivinen löytää, kun se on pienellä sivussa, ja siinä lukee 'opiskelijalle' ("Student: check out some potential research topics here.").

Tutkimusryhmän johtajana:
- Kirjautuminen onnistuu.
- Nyt näin, että lähettämäni palaute on tallentunut ja myös arkistointi toimii.
- Kun yritin lisätä julkaisua etusivulle, tuli Internal Service Error. (osoite: https://resgshowroom.herokuapp.com/update)
- Tutkimusaiheen lisääminen onnistuu. Voisi olla hyödyllistä rajoittaa ja tarkistaa syötteitä.
- Esittelytekstin ja nimen muokkaamisessa sama ongelma kuin tutkijasivulla. Uusi teksti tallentuu.

Yleistä: 
- Salasana näkyy, kun sitä kirjoittaa kirjautumisvaiheessa. Voisi harkita peittämistä.

Koodi:
- Jaettu loogisiin osioihin.
- Koodi ja skeema näyttävät hyvältä ja selkeältä.
- Tietoturva huomioitu, esim. csrf_token käytössä

**Comment by tspaanan** [comment]
Kiitos palautteesta! Löysitkin hyvän joukon tilanteita, joissa serveri ei selviä käyttäjän antamasta syötteestä (+ muutama mun oma ajatusvirhe sovelluslogiikan koodissa): kaikki sain onneksi korjattua. Myös käyttäjänäkökulman palaute oli arvokasta ja teki sovelluksesta paremman. Kiitos vielä!
